Wallet RCP create transaction
cypher-network/bamboo pull request #59
Opened 2021-09-05 22:55 UTC by pingpongsneak

- VDF cycle amounts lower than 5 secs causing timeouts and undesirable behaviour. 
- Removing coinsstake time-lock.
- Bring DateTimeToUnixTime into project as reference is undiscoverable.

2021-09-05 23:26 UTC, sanastasiou requested changes

2021-09-05 23:26 UTC, sanastasiou commented on bamwallet/HD/CommandReceiver.cs
> +                var t =  (int)(walletTransaction.Delay * 4.5 * 1000);
I am sorry, but I cannot in good faith accept this as a fix. It is equally wrong as the previous code. You cannot by any means guarantee that the time here will always be smaller or bigger than 5s. This depends on Operating System, System Resources, System Load and Hardware Specs of the system under test. 

It might work for some nodes most of the time, but it might fail for some other nodes all the time. If you think this is the correct approach feel free to merge this. But I highly assume this will fail again in the future.

In addition, I fail to understand how this function is supposed to work for the entire input range of "Delay" which is a user input per transaction. Sure perhaps it works for coin stake but it definitely will not work for any possible delay.

2021-09-05 23:26 UTC, sanastasiou commented on bamwallet/HD/CommandReceiver.cs
> +                    return TaskResult<Transaction>.CreateFailure(JObject.FromObject(new
See above.

2021-09-06 11:11 UTC, pingpongsneak commented on bamwallet/HD/CommandReceiver.cs
> +                var t =  (int)(walletTransaction.Delay * 4.5 * 1000);
I appreciate your work ethics but his code is going in and,  I appreciate your efforts.

2021-09-06 11:12 UTC, merged